/**
 * @openapi
 * /auth/password-reset:
 *   patch:
 *     summary: Reset user password
 *     description: >
 *       Resets the user's password using a provided reset token (passed as a query parameter)
 *       and a new password. The new password must be confirmed and meet the minimum length requirement.
 *       This endpoint is rate limited to 5 requests per minute.
 *     tags:
 *       - Auth
 *     parameters:
 *       - in: query
 *         name: resetToken
 *         required: true
 *         schema:
 *           type: string
 *         description: The password reset token generated by the forgot-password endpoint.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               newPassword:
 *                 type: string
 *                 example: "NewPassword123!"
 *               confirmNewPassword:
 *                 type: string
 *                 example: "NewPassword123!"
 *             required:
 *               - newPassword
 *               - confirmNewPassword
 *     responses:
 *       200:
 *         description: Password has been successfully reset.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: "success"
 *                 message:
 *                   type: string
 *                   example: "Password has been successfully reset"
 *       400:
 *         description: Validation error or bad request.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                 message:
 *                   type: string
 *             examples:
 *               missingResetToken:
 *                 summary: Missing reset token
 *                 value:
 *                   status: "fail"
 *                   message: "resetToken is required"
 *               missingNewPassword:
 *                 summary: Missing newPassword field
 *                 value:
 *                   status: "fail"
 *                   message: "newPassword is required"
 *               passwordMismatch:
 *                 summary: Passwords do not match
 *                 value:
 *                   status: "fail"
 *                   message: "newPassword and confirmNewPassword do not match"
 *               shortNewPassword:
 *                 summary: New password too short
 *                 value:
 *                   status: "fail"
 *                   message: "newPassword must be at least 8 characters long"
 *       429:
 *         $ref: '#/components/responses/RateLimitModerate'
 *       500:
 *         $ref: '#/components/responses/InternalError'
 */
